name: Ubuntu Test

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - "README.md"
      - "Makefile"
      - "Dockerfile"      

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        type: [personal, work]

    runs-on: ubuntu-latest
    steps:
      - name: Setup dotfiles
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          TYPE: ${{ matrix.type }}
          DOTFILES_DEBUG: 1
          DOTFILES_TEST_CONTAINER: 1
          EVENT_NAME: ${{ github.event_name }}
        run: |
          if [ "${EVENT_NAME}" == "push" ]; then
            BRANCH_NAME="${{ github.ref_name }}"
          elif [ "${EVENT_NAME}" == "pull_request" ]; then
            BRANCH_NAME="${{ github.head_ref }}"
          fi
          export BRANCH_NAME

          URL="https://raw.githubusercontent.com/ossistyle/dotfiles/${BRANCH_NAME}/setup.sh"
          echo "Download setup.sh from ${URL}"

          printf '${EMAIL_ADDRESS}\n${SYSTEM}\n' | bash -c "$(wget -qO - $URL)"
          #              │               │
          #              │               └─ Simulate inputting an system arcitecture into the config.
          #              └─ Simulate inputting an email address into the config.
          chezmoi dump-config -f yaml

      - name: Install latest bats-core
        run: |
          tmp_dir=$(mktemp -d /tmp/bats-core-XXXXX)
          git clone --depth 1 https://github.com/bats-core/bats-core.git "${tmp_dir}"
          cd "${tmp_dir}"
          sudo ./install.sh /usr/local
          rm -rf "${tmp_dir}"

      - name: Test file existence
        env:
          TYPE: ${{ matrix.type }}
        run: |
          cd $(chezmoi source-path)/../
          # bats tests/files/common.bats
          bats --filter-tags common,ubuntu:${TYPE} \
            --print-output-on-failure \
            tests/files/linux/ubuntu.bats